#!/bin/bash
wget https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_5.1.4_amd64.deb
sudo apt-get install -y adduser libfontconfig
sudo dpkg -i grafana_5.1.4_amd64.deb
sudo apt-get update
sudo apt-get install grafana
sudo service grafana-server start
sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password mysql'
sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password mysql'
sudo apt-get -y install mysql-server
mysql -u root -p <db.sql
sudo service mysql start
sudo apt-get install -y nodejs
sudo apt-get install npm
sudo npm cache clean -f
npm config set strict-ssl false
sudo npm install -g n
sudo n latest
npm install node-ipc
npm install socket.io
node main.js
curl --user admin:admin 'http://localhost:3000/api/datasources' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"name":"infiniswap","type":"mysql","url":"http://localhost:3306","access":"proxy","basicAuth":false}'